
!-------------------------------------------------------------------------------
!> module scale_atmos_dyn_fvm_flux_cd8
!!
!! @par Description
!!          FVM flux scheme with the cd8 order
!!
!! @author Team SCALE
!!
!<
!-------------------------------------------------------------------------------
! Warning: This file was generated from atmos-rm/dynamics/scale_atmos_dyn_fvm_flux_udcd.F90.erb.
!          Do not edit this file.
!-------------------------------------------------------------------------------
#include "scalelib.h"
module scale_atmos_dyn_fvm_flux_cd8
  !-----------------------------------------------------------------------------
  !
  !++ used modules
  !
  use scale_precision
  use scale_io
  use scale_prof
  use scale_atmos_grid_cartesC_index
  use scale_index
  use scale_tracer
  use scale_prc
#ifdef DEBUG
  use scale_debug, only: &
     CHECK
  use scale_const, only: &
     UNDEF  => CONST_UNDEF, &
     IUNDEF => CONST_UNDEF2
#endif
  !-----------------------------------------------------------------------------
  implicit none
  private
  !-----------------------------------------------------------------------------
  !
  !++ Public procedure
  !
  public :: ATMOS_DYN_FVM_flux_valueW_Z_cd8

  public :: ATMOS_DYN_FVM_fluxZ_XYZ_cd8
  public :: ATMOS_DYN_FVM_fluxX_XYZ_cd8
  public :: ATMOS_DYN_FVM_fluxY_XYZ_cd8

  public :: ATMOS_DYN_FVM_fluxZ_XYW_cd8
  public :: ATMOS_DYN_FVM_fluxJ13_XYW_cd8
  public :: ATMOS_DYN_FVM_fluxJ23_XYW_cd8
  public :: ATMOS_DYN_FVM_fluxX_XYW_cd8
  public :: ATMOS_DYN_FVM_fluxY_XYW_cd8

  public :: ATMOS_DYN_FVM_fluxZ_UYZ_cd8
  public :: ATMOS_DYN_FVM_fluxJ13_UYZ_cd8
  public :: ATMOS_DYN_FVM_fluxJ23_UYZ_cd8
  public :: ATMOS_DYN_FVM_fluxX_UYZ_cd8
  public :: ATMOS_DYN_FVM_fluxY_UYZ_cd8

  public :: ATMOS_DYN_FVM_fluxZ_XVZ_cd8
  public :: ATMOS_DYN_FVM_fluxJ13_XVZ_cd8
  public :: ATMOS_DYN_FVM_fluxJ23_XVZ_cd8
  public :: ATMOS_DYN_FVM_fluxX_XVZ_cd8
  public :: ATMOS_DYN_FVM_fluxY_XVZ_cd8

  !-----------------------------------------------------------------------------
  !
  !++ Public parameters & variables
  !
  !-----------------------------------------------------------------------------
  !
  !++ Private procedure
  !
#if 1
! weight for full-level k+1; weight for k is 1 - F2H(k,q)
#define F2H(k,q) (CDZ(k)*GSQRT(k,i,j)/(CDZ(k)*GSQRT(k,i,j)+CDZ(k+1)*GSQRT(k+1,i,j)))
#else
#define F2H(k,q) 0.5_RP
#endif
  !-----------------------------------------------------------------------------
  !
  !++ Private parameters & variables
  !

  real(RP), parameter :: F2  =  0.5_RP          ! F2 is always used to calculate flux near boundary.


  real(RP), parameter :: F41 =  7.0_RP/12.0_RP
  real(RP), parameter :: F42 = -1.0_RP/12.0_RP


  real(RP), parameter :: F61 = 37.0_RP/60.0_RP
  real(RP), parameter :: F62 = -8.0_RP/60.0_RP
  real(RP), parameter :: F63 =  1.0_RP/60.0_RP


  real(RP), parameter :: F81 =  533.0_RP/840.0_RP
  real(RP), parameter :: F82 = -139.0_RP/840.0_RP
  real(RP), parameter :: F83 =   29.0_RP/840.0_RP
  real(RP), parameter :: F84 =   -3.0_RP/840.0_RP



contains
  !-----------------------------------------------------------------------------
  !> value at XYW
!OCL SERIAL
  subroutine ATMOS_DYN_FVM_flux_valueW_Z_cd8( &
       valW,             &
       mflx, val, GSQRT, &
       CDZ               )
    !$acc routine vector
    implicit none

    real(RP), intent(out) :: valW (KA)
    real(RP), intent(in)  :: mflx (KA)
    real(RP), intent(in)  :: val  (KA)
    real(RP), intent(in)  :: GSQRT(KA)
    real(RP), intent(in)  :: CDZ  (KA)

    integer  :: k
    !---------------------------------------------------------------------------

    do k = KS+3, KE-4
#ifdef DEBUG
       call CHECK( __LINE__, mflx(k) )

       call CHECK( __LINE__, val(k) )
       call CHECK( __LINE__, val(k+1) )

       call CHECK( __LINE__, val(k-1) )
       call CHECK( __LINE__, val(k+2) )

       call CHECK( __LINE__, val(k-2) )
       call CHECK( __LINE__, val(k+3) )

       call CHECK( __LINE__, val(k-3) )
       call CHECK( __LINE__, val(k+4) )

#endif
       valW(k)       = F81 * ( val(k+1)+val(k) ) &
                     + F82 * ( val(k+2)+val(k-1) ) &
                     + F83 * ( val(k+3)+val(k-2) ) &
                     + F84 * ( val(k+4)+val(k-3) )
    enddo
#ifdef DEBUG
    k = IUNDEF
#endif

#ifdef DEBUG

       call CHECK( __LINE__, mflx(KS) )
       call CHECK( __LINE__, val(KS  ) )
       call CHECK( __LINE__, val(KS+1) )
       call CHECK( __LINE__, mflx(KE-1) )
       call CHECK( __LINE__, val(KE  ) )
       call CHECK( __LINE__, val(KE-1) )

       call CHECK( __LINE__, mflx(KS+1) )
       call CHECK( __LINE__, val(KS+2  ) )
       call CHECK( __LINE__, val(KS+3) )
       call CHECK( __LINE__, mflx(KE-2) )
       call CHECK( __LINE__, val(KE-2  ) )
       call CHECK( __LINE__, val(KE-3) )

       call CHECK( __LINE__, mflx(KS+2) )
       call CHECK( __LINE__, val(KS+4  ) )
       call CHECK( __LINE__, val(KS+5) )
       call CHECK( __LINE__, mflx(KE-3) )
       call CHECK( __LINE__, val(KE-4  ) )
       call CHECK( __LINE__, val(KE-5) )

#endif

       valW(KS) = F2 * ( val(KS+1)+val(KS) )
       valW(KE-1) = F2 * ( val(KE)+val(KE-1) )

       valW(KS+1) = F41 * ( val(KS+2)+val(KS+1) ) &
                     + F42 * ( val(KS+3)+val(KS) )
       valW(KE-2) = F41 * ( val(KE-1)+val(KE-2) ) &
                     + F42 * ( val(KE)+val(KE-3) )

       valW(KS+2) = F61 * ( val(KS+3)+val(KS+2) ) &
                     + F62 * ( val(KS+4)+val(KS+1) ) &
                     + F63 * ( val(KS+5)+val(KS) )
       valW(KE-3) = F61 * ( val(KE-2)+val(KE-3) ) &
                     + F62 * ( val(KE-1)+val(KE-4) ) &
                     + F63 * ( val(KE)+val(KE-5) )


    return
  end subroutine ATMOS_DYN_FVM_flux_ValueW_Z_cd8

  !-----------------------------------------------------------------------------
  !> calculation z-flux at XYZ
  subroutine ATMOS_DYN_FVM_fluxZ_XYZ_cd8( &
       flux,              &
       mflx, val, GSQRT,  &
       num_diff,          &
       CDZ,               &
       IIS, IIE, JJS, JJE )
    use scale_const, only: &
      EPS => CONST_EPS
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mflx    (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k, vel)                    &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mflx,val,flux,GSQRT,num_diff,EPS)

    !$acc data copy(flux) copyin(mflx, val, GSQRT, num_diff, CDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
#ifdef DEBUG
       call CHECK( __LINE__, mflx(k,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k+1,i,j) )

       call CHECK( __LINE__, val(k-1,i,j) )
       call CHECK( __LINE__, val(k+2,i,j) )

       call CHECK( __LINE__, val(k-2,i,j) )
       call CHECK( __LINE__, val(k+3,i,j) )

       call CHECK( __LINE__, val(k-3,i,j) )
       call CHECK( __LINE__, val(k+4,i,j) )

#endif
       vel = mflx(k,i,j)
       flux(k,i,j) = vel &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
#ifdef DEBUG

       call CHECK( __LINE__, mflx(KS,i,j) )
       call CHECK( __LINE__, val(KS  ,i,j) )
       call CHECK( __LINE__, val(KS+1,i,j) )
       call CHECK( __LINE__, mflx(KE-1,i,j) )
       call CHECK( __LINE__, val(KE  ,i,j) )
       call CHECK( __LINE__, val(KE-1,i,j) )

       call CHECK( __LINE__, mflx(KS+1,i,j) )
       call CHECK( __LINE__, val(KS+2  ,i,j) )
       call CHECK( __LINE__, val(KS+3,i,j) )
       call CHECK( __LINE__, mflx(KE-2,i,j) )
       call CHECK( __LINE__, val(KE-2  ,i,j) )
       call CHECK( __LINE__, val(KE-3,i,j) )

       call CHECK( __LINE__, mflx(KS+2,i,j) )
       call CHECK( __LINE__, val(KS+4  ,i,j) )
       call CHECK( __LINE__, val(KS+5,i,j) )
       call CHECK( __LINE__, mflx(KE-3,i,j) )
       call CHECK( __LINE__, val(KE-4  ,i,j) )
       call CHECK( __LINE__, val(KE-5,i,j) )

#endif
       flux(KS-1,i,j) = 0.0_RP

       vel = mflx(KS,i,j)
       flux(KS,i,j) = vel &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS,i,j) * num_diff(KS,i,j)
       vel = mflx(KE-1,i,j)
       flux(KE-1,i,j) = vel &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) ) &
                   + GSQRT(KE-1,i,j) * num_diff(KE-1,i,j)

       vel = mflx(KS+1,i,j)
       flux(KS+1,i,j) = vel &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+1,i,j) * num_diff(KS+1,i,j)
       vel = mflx(KE-2,i,j)
       flux(KE-2,i,j) = vel &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) ) &
                   + GSQRT(KE-2,i,j) * num_diff(KE-2,i,j)

       vel = mflx(KS+2,i,j)
       flux(KS+2,i,j) = vel &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+2,i,j) * num_diff(KS+2,i,j)
       vel = mflx(KE-3,i,j)
       flux(KE-3,i,j) = vel &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) ) &
                   + GSQRT(KE-3,i,j) * num_diff(KE-3,i,j)

       flux(KE  ,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxZ_XYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation X-flux at XYZ
  subroutine ATMOS_DYN_FVM_fluxX_XYZ_cd8( &
       flux,              &
       mflx, val, GSQRT,  &
       num_diff,          &
       CDZ,               &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mflx    (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ(KA)
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mflx,val,flux,GSQRT,num_diff)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS-1, IIE
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mflx(k,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i+1,j) )

       call CHECK( __LINE__, val(k,i-1,j) )
       call CHECK( __LINE__, val(k,i+2,j) )

       call CHECK( __LINE__, val(k,i-2,j) )
       call CHECK( __LINE__, val(k,i+3,j) )

       call CHECK( __LINE__, val(k,i-3,j) )
       call CHECK( __LINE__, val(k,i+4,j) )

#endif
       vel = mflx(k,i,j)
       flux(k,i,j) = vel &
                   * ( F81 * ( val(k,i+1,j)+val(k,i,j) ) &
                     + F82 * ( val(k,i+2,j)+val(k,i-1,j) ) &
                     + F83 * ( val(k,i+3,j)+val(k,i-2,j) ) &
                     + F84 * ( val(k,i+4,j)+val(k,i-3,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxX_XYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation Y-flux at XYZ
  subroutine ATMOS_DYN_FVM_fluxY_XYZ_cd8( &
       flux,              &
       mflx, val, GSQRT,  &
       num_diff,          &
       CDZ,               &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mflx    (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ(KA)
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mflx,val,flux,GSQRT,num_diff)
    !$acc kernels
    do j = JJS-1, JJE
    do i = IIS, IIE
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mflx(k,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j-1) )
       call CHECK( __LINE__, val(k,i,j+2) )

       call CHECK( __LINE__, val(k,i,j-2) )
       call CHECK( __LINE__, val(k,i,j+3) )

       call CHECK( __LINE__, val(k,i,j-3) )
       call CHECK( __LINE__, val(k,i,j+4) )

#endif
       vel = mflx(k,i,j)
       flux(k,i,j) = vel &
                   * ( F81 * ( val(k,i,j+1)+val(k,i,j) ) &
                     + F82 * ( val(k,i,j+2)+val(k,i,j-1) ) &
                     + F83 * ( val(k,i,j+3)+val(k,i,j-2) ) &
                     + F84 * ( val(k,i,j+4)+val(k,i,j-3) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxY_XYZ_cd8


  !-----------------------------------------------------------------------------
  !> calculation z-flux at XYW
  subroutine ATMOS_DYN_FVM_fluxZ_XYW_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J33G,       &
       num_diff,          &
       CDZ, FDZ,          &
       dtrk,              &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J33G
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    real(RP), intent(in)  :: FDZ     (KA-1)
    real(RP), intent(in)  :: dtrk
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    ! note than z-index is added by -1

    !$omp parallel default(none) private(i,j,k,vel)  &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,flux,J33G,GSQRT,num_diff,DENS,FDZ,dtrk)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, num_diff, CDZ, FDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+4, KE-3
#ifdef DEBUG
       call CHECK( __LINE__, mom(k-1,i,j) )
       call CHECK( __LINE__, mom(k  ,i,j) )

       call CHECK( __LINE__, val(k-1,i,j) )
       call CHECK( __LINE__, val(k,i,j) )

       call CHECK( __LINE__, val(k-2,i,j) )
       call CHECK( __LINE__, val(k+1,i,j) )

       call CHECK( __LINE__, val(k-3,i,j) )
       call CHECK( __LINE__, val(k+2,i,j) )

       call CHECK( __LINE__, val(k-4,i,j) )
       call CHECK( __LINE__, val(k+3,i,j) )

#endif
       vel = ( 0.5_RP * ( mom(k-1,i,j) &
                        + mom(k,i,j) ) ) &
           / DENS(k,i,j)
       flux(k-1,i,j) = J33G * vel &
                   * ( F81 * ( val(k,i,j)+val(k-1,i,j) ) &
                     + F82 * ( val(k+1,i,j)+val(k-2,i,j) ) &
                     + F83 * ( val(k+2,i,j)+val(k-3,i,j) ) &
                     + F84 * ( val(k+3,i,j)+val(k-4,i,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
#ifdef DEBUG

       call CHECK( __LINE__, val(KS,i,j) )
       call CHECK( __LINE__, val(KS+1,i,j) )
       call CHECK( __LINE__, val(KS+2,i,j) )
       call CHECK( __LINE__, val(KS+3,i,j) )
       call CHECK( __LINE__, val(KS+4,i,j) )
       call CHECK( __LINE__, val(KS+5,i,j) )


       call CHECK( __LINE__, val(KE-5,i,j) )
       call CHECK( __LINE__, val(KE-4,i,j) )
       call CHECK( __LINE__, val(KE-3,i,j) )
       call CHECK( __LINE__, val(KE-2,i,j) )
       call CHECK( __LINE__, val(KE-1,i,j) )

#endif
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS.
       ! The flux at KS can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP ! k = KS

       vel = ( 0.5_RP * ( mom(KS,i,j) &
                        + mom(KS+1,i,j) ) ) &
           / DENS(KS+1,i,j)
       flux(KS,i,j) = J33G * vel &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+1,i,j) * num_diff(KS+1,i,j) ! k = KS+1

       vel = ( 0.5_RP * ( mom(KS+1,i,j) &
                        + mom(KS+2,i,j) ) ) &
           / DENS(KS+2,i,j)
       flux(KS+1,i,j) = J33G * vel &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+2,i,j) * num_diff(KS+2,i,j) ! k = KS+2

       vel = ( 0.5_RP * ( mom(KS+2,i,j) &
                        + mom(KS+3,i,j) ) ) &
           / DENS(KS+3,i,j)
       flux(KS+2,i,j) = J33G * vel &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+3,i,j) * num_diff(KS+3,i,j) ! k = KS+3



       vel = ( 0.5_RP * ( mom(KE-3,i,j) &
                        + mom(KE-2,i,j) ) ) &
           / DENS(KE-1,i,j)
       flux(KE-3,i,j) = J33G * vel &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) ) &
                   + GSQRT(KE-2,i,j) * num_diff(KE-2,i,j) ! k = KE-2

       vel = ( 0.5_RP * ( mom(KE-2,i,j) &
                        + mom(KE-1,i,j) ) ) &
           / DENS(KE-1,i,j)
       flux(KE-2,i,j) = J33G * vel &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) ) &
                   + GSQRT(KE-1,i,j) * num_diff(KE-1,i,j) ! k = KE-1

       flux(KE-1,i,j) = 0.0_RP ! k = KE
       flux(KE  ,i,j) = 0.0_RP ! k = KE+1
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel

    return
  end subroutine ATMOS_DYN_FVM_fluxZ_XYW_cd8


  !-----------------------------------------------------------------------------
  !> calculation J13-flux at XYW
  subroutine ATMOS_DYN_FVM_fluxJ13_XYW_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J13G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J13G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J13G,MAPF)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J13G, MAPF, CDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-3
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i-1,j) ) ) &
           / DENS(k,i,j)
       vel = vel * J13G(k,i,j)
       flux(k-1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F81 * ( val(k,i,j)+val(k-1,i,j) ) &
                     + F82 * ( val(k+1,i,j)+val(k-2,i,j) ) &
                     + F83 * ( val(k+2,i,j)+val(k-3,i,j) ) &
                     + F84 * ( val(k+3,i,j)+val(k-4,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS.
       ! The flux at KS can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP ! k = KS

       ! physically incorrect but for numerical stability
       vel = ( ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i-1,j) ) ) / DENS(KS+1,i,j) &
             + ( 0.5_RP * ( mom(KS,i,j)+mom(KS,i-1,j) ) ) / DENS(KS  ,i,j) ) * 0.5_RP
!       vel = ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i-1,j) ) ) &
!           / DENS(KS+1,i,j)
       vel = vel * J13G(KS+1,i,j)
       flux(KS,i,j) =  vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) ! k = KS+1

       vel = ( 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i-1,j) ) ) &
           / DENS(KS+2,i,j)
       vel = vel * J13G(KS,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) ! k = KS+2


       vel = ( 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i-1,j) ) ) &
           / DENS(KE-1,i,j)
       vel = vel * J13G(KE-1,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KE-1,i,j)+val(KE-2,i,j) ) ) ! k = KE-3

       vel = ( 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i-1,j) ) ) &
           / DENS(KE-2,i,j)
       vel = vel * J13G(KE-2,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F42 * ( val(KE-1,i,j)+val(KE-4,i,j) ) ) ! k = KE-4

       flux(KE-1,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel

    return
  end subroutine ATMOS_DYN_FVM_fluxJ13_XYW_cd8

  !-----------------------------------------------------------------------------
  !> calculation J23-flux at XYW
  subroutine ATMOS_DYN_FVM_fluxJ23_XYW_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J23G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J23G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J23G,MAPF)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J23G, MAPF, CDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-3
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i,j-1) ) ) &
           / DENS(k,i,j)
       vel = vel * J23G(k,i,j)
       flux(k-1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F81 * ( val(k,i,j)+val(k-1,i,j) ) &
                     + F82 * ( val(k+1,i,j)+val(k-2,i,j) ) &
                     + F83 * ( val(k+2,i,j)+val(k-3,i,j) ) &
                     + F84 * ( val(k+3,i,j)+val(k-4,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS.
       ! The flux at KS can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP ! k = KS

       ! physically incorrect but for numerical stability
       vel = ( ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i,j-1) ) ) / DENS(KS+1,i,j) &
             + ( 0.5_RP * ( mom(KS,i,j)+mom(KS,i,j-1) ) ) / DENS(KS  ,i,j) ) * 0.5_RP
!       vel = ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i,j-1) ) ) &
!           / DENS(KS+1,i,j)
       vel = vel * J23G(KS+1,i,j)
       flux(KS,i,j) =  vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) ! k = KS+1

       vel = ( 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i,j-1) ) ) &
           / DENS(KS+2,i,j)
       vel = vel * J23G(KS,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) ! k = KS+2


       vel = ( 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i,j-1) ) ) &
           / DENS(KE-1,i,j)
       vel = vel * J23G(KE-1,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KE-1,i,j)+val(KE-2,i,j) ) ) ! k = KE-3

       vel = ( 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i,j-1) ) ) &
           / DENS(KE-2,i,j)
       vel = vel * J23G(KE-2,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F42 * ( val(KE-1,i,j)+val(KE-4,i,j) ) ) ! k = KE-4

       flux(KE-1,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel

    return
  end subroutine ATMOS_DYN_FVM_fluxJ23_XYW_cd8


  !-----------------------------------------------------------------------------
  !> calculation X-flux at XYW
  subroutine ATMOS_DYN_FVM_fluxX_XYW_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_UYZ_k, f2h2_UYZ_k
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_UYZ_k,f2h2_UYZ_k) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff) &
    !$omp shared(CDZ)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, MAPF, num_diff, CDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS-1, IIE
    do k = KS, KE-1
#ifdef DEBUG
       call CHECK( __LINE__, mom(k  ,i,j) )
       call CHECK( __LINE__, mom(k+1,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i+1,j) )

       call CHECK( __LINE__, val(k,i-1,j) )
       call CHECK( __LINE__, val(k,i+2,j) )

       call CHECK( __LINE__, val(k,i-2,j) )
       call CHECK( __LINE__, val(k,i+3,j) )

       call CHECK( __LINE__, val(k,i-3,j) )
       call CHECK( __LINE__, val(k,i+4,j) )

#endif
       f2h1_UYZ_k = F2H(k,I_UYZ)
       f2h2_UYZ_k = 1.0_RP - f2h1_UYZ_k
       vel = ( f2h1_UYZ_k * mom(k+1,i,j) &
             + f2h2_UYZ_k * mom(k,i,j) ) &
           / ( f2h1_UYZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i+1,j) ) &
             + f2h2_UYZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i+1,j) ) )
       flux(k,i,j) = GSQRT(k,i,j) / MAPF(i,j,+2) * vel &
                   * ( F81 * ( val(k,i+1,j)+val(k,i,j) ) &
                     + F82 * ( val(k,i+2,j)+val(k,i-1,j) ) &
                     + F83 * ( val(k,i+3,j)+val(k,i-2,j) ) &
                     + F84 * ( val(k,i+4,j)+val(k,i-3,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS-1, IIE
       flux(KE,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxX_XYW_cd8

  !-----------------------------------------------------------------------------
  !> calculation Y-flux at XYW
  subroutine ATMOS_DYN_FVM_fluxY_XYW_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XVZ_k, f2h2_XVZ_k
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XVZ_k,f2h2_XVZ_k) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff) &
    !$omp shared(CDZ)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, MAPF, num_diff, CDZ)

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS-1, JJE
    do i = IIS, IIE
    do k = KS, KE-1
#ifdef DEBUG
       call CHECK( __LINE__, mom(k  ,i,j) )
       call CHECK( __LINE__, mom(k+1,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j-1) )
       call CHECK( __LINE__, val(k,i,j+2) )

       call CHECK( __LINE__, val(k,i,j-2) )
       call CHECK( __LINE__, val(k,i,j+3) )

       call CHECK( __LINE__, val(k,i,j-3) )
       call CHECK( __LINE__, val(k,i,j+4) )

#endif
       f2h1_XVZ_k = F2H(k,I_XVZ)
       f2h2_XVZ_k = 1.0_RP - f2h1_XVZ_k
       vel = ( f2h1_XVZ_k * mom(k+1,i,j) &
             + f2h2_XVZ_k * mom(k,i,j) ) &
           / ( f2h1_XVZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i,j+1) ) &
             + f2h2_XVZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i,j+1) ) )
       flux(k,i,j) = GSQRT(k,i,j) / MAPF(i,j,+1) * vel &
                   * ( F81 * ( val(k,i,j+1)+val(k,i,j) ) &
                     + F82 * ( val(k,i,j+2)+val(k,i,j-1) ) &
                     + F83 * ( val(k,i,j+3)+val(k,i,j-2) ) &
                     + F84 * ( val(k,i,j+4)+val(k,i,j-3) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS-1, JJE
    do i = IIS, IIE
       flux(KE,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$acc end data

    !$omp end parallel
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxY_XYW_cd8


  !-----------------------------------------------------------------------------
  !> calculation z-flux at UY
  subroutine ATMOS_DYN_FVM_fluxZ_UYZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J33G,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J33G
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XYZ_k, f2h2_XYZ_k
    real(RP) :: f2h1_XYZ_KS, f2h2_XYZ_KS
    real(RP) :: f2h1_XYZ_KEm1, f2h2_XYZ_KEm1
    real(RP) :: f2h1_XYZ_KSp1, f2h2_XYZ_KSp1
    real(RP) :: f2h1_XYZ_KEm2, f2h2_XYZ_KEm2
    real(RP) :: f2h1_XYZ_KSp2, f2h2_XYZ_KSp2
    real(RP) :: f2h1_XYZ_KEm3, f2h2_XYZ_KEm3
    real(RP) :: f2h1_UYZ_k, f2h2_UYZ_k
    real(RP) :: f2h1_UYZ_KS, f2h2_UYZ_KS
    real(RP) :: f2h1_UYZ_KEm1, f2h2_UYZ_KEm1
    real(RP) :: f2h1_UYZ_KSp1, f2h2_UYZ_KSp1
    real(RP) :: f2h1_UYZ_KEm2, f2h2_UYZ_KEm2
    real(RP) :: f2h1_UYZ_KSp2, f2h2_UYZ_KSp2
    real(RP) :: f2h1_UYZ_KEm3, f2h2_UYZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XYZ_k,f2h2_XYZ_k,f2h1_XYZ_KS,f2h2_XYZ_KS) &
    !$omp private(f2h1_XYZ_KEm1,f2h2_XYZ_KEm1,f2h1_XYZ_KSp1,f2h2_XYZ_KSp1) &
    !$omp private(f2h1_XYZ_KEm2,f2h2_XYZ_KEm2,f2h1_XYZ_KSp2,f2h2_XYZ_KSp2) &
    !$omp private(f2h1_XYZ_KEm3,f2h2_XYZ_KEm3,f2h1_UYZ_k,f2h2_UYZ_k) &
    !$omp private(f2h1_UYZ_KS,f2h2_UYZ_KS,f2h1_UYZ_KEm1,f2h2_UYZ_KEm1) &
    !$omp private(f2h1_UYZ_KSp1,f2h2_UYZ_KSp1,f2h1_UYZ_KEm2,f2h2_UYZ_KEm2) &
    !$omp private(f2h1_UYZ_KSp2,f2h2_UYZ_KSp2,f2h1_UYZ_KEm3,f2h2_UYZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J33G,GSQRT,num_diff) &
    !$omp shared(CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, num_diff, CDZ)


    if ( TwoD ) then

    !$omp do OMP_SCHEDULE_
    !$acc kernels
    do j = JJS, JJE
    do k = KS+3, KE-4
       i = IIS
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k+1,i,j) )

       call CHECK( __LINE__, val(k-1,i,j) )
       call CHECK( __LINE__, val(k+2,i,j) )

       call CHECK( __LINE__, val(k-2,i,j) )
       call CHECK( __LINE__, val(k+3,i,j) )

       call CHECK( __LINE__, val(k-3,i,j) )
       call CHECK( __LINE__, val(k+4,i,j) )

#endif
       f2h1_XYZ_k = F2H(k,I_XYZ)
       f2h2_XYZ_k = 1.0_RP - f2h1_XYZ_k
       vel = ( mom(k,i,j) ) &
           / ( f2h1_XYZ_k * DENS(k+1,i,j) &
             + f2h2_XYZ_k * DENS(k,i,j) )
       flux(k,i,j) = J33G * vel &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_
    !$acc kernels
    do j = JJS, JJE
       i = IIS
#ifdef DEBUG

       call CHECK( __LINE__, mom(KS,i  ,j) )
       call CHECK( __LINE__, val(KS+1,i,j) )
       call CHECK( __LINE__, val(KS,i,j) )

       call CHECK( __LINE__, mom(KS+1,i  ,j) )
       call CHECK( __LINE__, val(KS+3,i,j) )
       call CHECK( __LINE__, val(KS+2,i,j) )

       call CHECK( __LINE__, mom(KS+2,i  ,j) )
       call CHECK( __LINE__, val(KS+5,i,j) )
       call CHECK( __LINE__, val(KS+4,i,j) )

#endif
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_XYZ_KS = F2H(KS,I_XYZ)
       f2h2_XYZ_KS = 1.0_RP - f2h1_XYZ_KS
       vel = ( mom(KS,i,j) ) &
           / ( f2h1_XYZ_KS * DENS(KS+1,i,j) &
             + f2h2_XYZ_KS * DENS(KS,i,j) )
       flux(KS,i,j) = J33G * vel &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS,i,j) * num_diff(KS,i,j)
       f2h1_XYZ_KEm1 = F2H(KE-1,I_XYZ)
       f2h2_XYZ_KEm1 = 1.0_RP - f2h1_XYZ_KEm1
       vel = ( mom(KE-1,i,j) ) &
           / ( f2h1_XYZ_KEm1 * DENS(KE,i,j) &
             + f2h2_XYZ_KEm1 * DENS(KE-1,i,j) )
       flux(KE-1,i,j) = J33G * vel &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) ) &
                   + GSQRT(KE-1,i,j) * num_diff(KE-1,i,j)

       f2h1_XYZ_KSp1 = F2H(KS+1,I_XYZ)
       f2h2_XYZ_KSp1 = 1.0_RP - f2h1_XYZ_KSp1
       vel = ( mom(KS+1,i,j) ) &
           / ( f2h1_XYZ_KSp1 * DENS(KS+2,i,j) &
             + f2h2_XYZ_KSp1 * DENS(KS+1,i,j) )
       flux(KS+1,i,j) = J33G * vel &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+1,i,j) * num_diff(KS+1,i,j)
       f2h1_XYZ_KEm2 = F2H(KE-2,I_XYZ)
       f2h2_XYZ_KEm2 = 1.0_RP - f2h1_XYZ_KEm2
       vel = ( mom(KE-2,i,j) ) &
           / ( f2h1_XYZ_KEm2 * DENS(KE-1,i,j) &
             + f2h2_XYZ_KEm2 * DENS(KE-2,i,j) )
       flux(KE-2,i,j) = J33G * vel &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) ) &
                   + GSQRT(KE-2,i,j) * num_diff(KE-2,i,j)

       f2h1_XYZ_KSp2 = F2H(KS+2,I_XYZ)
       f2h2_XYZ_KSp2 = 1.0_RP - f2h1_XYZ_KSp2
       vel = ( mom(KS+2,i,j) ) &
           / ( f2h1_XYZ_KSp2 * DENS(KS+3,i,j) &
             + f2h2_XYZ_KSp2 * DENS(KS+2,i,j) )
       flux(KS+2,i,j) = J33G * vel &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+2,i,j) * num_diff(KS+2,i,j)
       f2h1_XYZ_KEm3 = F2H(KE-3,I_XYZ)
       f2h2_XYZ_KEm3 = 1.0_RP - f2h1_XYZ_KEm3
       vel = ( mom(KE-3,i,j) ) &
           / ( f2h1_XYZ_KEm3 * DENS(KE-2,i,j) &
             + f2h2_XYZ_KEm3 * DENS(KE-3,i,j) )
       flux(KE-3,i,j) = J33G * vel &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) ) &
                   + GSQRT(KE-3,i,j) * num_diff(KE-3,i,j)

       flux(KE,i,j) = 0.0_RP
    enddo
    !$acc end kernels
    !$omp end do nowait

    else


    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i,j) )
       call CHECK( __LINE__, mom(k,i+1,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k+1,i,j) )

       call CHECK( __LINE__, val(k-1,i,j) )
       call CHECK( __LINE__, val(k+2,i,j) )

       call CHECK( __LINE__, val(k-2,i,j) )
       call CHECK( __LINE__, val(k+3,i,j) )

       call CHECK( __LINE__, val(k-3,i,j) )
       call CHECK( __LINE__, val(k+4,i,j) )

#endif
       f2h1_UYZ_k = F2H(k,I_UYZ)
       f2h2_UYZ_k = 1.0_RP - f2h1_UYZ_k
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i+1,j) ) ) &
           / ( f2h1_UYZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i+1,j) ) &
             + f2h2_UYZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i+1,j) ) )
       flux(k,i,j) = J33G * vel &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
#ifdef DEBUG

       call CHECK( __LINE__, mom(KS,i  ,j) )
       call CHECK( __LINE__, mom(KS,i+1,j) )
       call CHECK( __LINE__, val(KS+1,i,j) )
       call CHECK( __LINE__, val(KS,i,j) )

       call CHECK( __LINE__, mom(KS+1,i  ,j) )
       call CHECK( __LINE__, mom(KS+1,i+1,j) )
       call CHECK( __LINE__, val(KS+3,i,j) )
       call CHECK( __LINE__, val(KS+2,i,j) )

       call CHECK( __LINE__, mom(KS+2,i  ,j) )
       call CHECK( __LINE__, mom(KS+2,i+1,j) )
       call CHECK( __LINE__, val(KS+5,i,j) )
       call CHECK( __LINE__, val(KS+4,i,j) )

#endif
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_UYZ_KS = F2H(KS,I_UYZ)
       f2h2_UYZ_KS = 1.0_RP - f2h1_UYZ_KS
       vel = ( 0.5_RP * ( mom(KS,i,j)+mom(KS,i+1,j) ) ) &
           / ( f2h1_UYZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) &
             + f2h2_UYZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i+1,j) ) )
       flux(KS,i,j) = J33G * vel &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS,i,j) * num_diff(KS,i,j)
       f2h1_UYZ_KEm1 = F2H(KE-1,I_UYZ)
       f2h2_UYZ_KEm1 = 1.0_RP - f2h1_UYZ_KEm1
       vel = ( 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i+1,j) ) ) &
           / ( f2h1_UYZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i+1,j) ) &
             + f2h2_UYZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) )
       flux(KE-1,i,j) = J33G * vel &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) ) &
                   + GSQRT(KE-1,i,j) * num_diff(KE-1,i,j)

       f2h1_UYZ_KSp1 = F2H(KS+1,I_UYZ)
       f2h2_UYZ_KSp1 = 1.0_RP - f2h1_UYZ_KSp1
       vel = ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i+1,j) ) ) &
           / ( f2h1_UYZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) &
             + f2h2_UYZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) )
       flux(KS+1,i,j) = J33G * vel &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+1,i,j) * num_diff(KS+1,i,j)
       f2h1_UYZ_KEm2 = F2H(KE-2,I_UYZ)
       f2h2_UYZ_KEm2 = 1.0_RP - f2h1_UYZ_KEm2
       vel = ( 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i+1,j) ) ) &
           / ( f2h1_UYZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) &
             + f2h2_UYZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) )
       flux(KE-2,i,j) = J33G * vel &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) ) &
                   + GSQRT(KE-2,i,j) * num_diff(KE-2,i,j)

       f2h1_UYZ_KSp2 = F2H(KS+2,I_UYZ)
       f2h2_UYZ_KSp2 = 1.0_RP - f2h1_UYZ_KSp2
       vel = ( 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i+1,j) ) ) &
           / ( f2h1_UYZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i+1,j) ) &
             + f2h2_UYZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) )
       flux(KS+2,i,j) = J33G * vel &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+2,i,j) * num_diff(KS+2,i,j)
       f2h1_UYZ_KEm3 = F2H(KE-3,I_UYZ)
       f2h2_UYZ_KEm3 = 1.0_RP - f2h1_UYZ_KEm3
       vel = ( 0.5_RP * ( mom(KE-3,i,j)+mom(KE-3,i+1,j) ) ) &
           / ( f2h1_UYZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) &
             + f2h2_UYZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i+1,j) ) )
       flux(KE-3,i,j) = J33G * vel &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) ) &
                   + GSQRT(KE-3,i,j) * num_diff(KE-3,i,j)

       flux(KE,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    end if


    !$acc end data

    !$omp end parallel
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxZ_UYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation J13-flux at UYZ
  subroutine ATMOS_DYN_FVM_fluxJ13_UYZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J13G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J13G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_UYZ_k, f2h2_UYZ_k
    real(RP) :: f2h1_UYZ_KS, f2h2_UYZ_KS
    real(RP) :: f2h1_UYZ_KEm1, f2h2_UYZ_KEm1
    real(RP) :: f2h1_UYZ_KSp1, f2h2_UYZ_KSp1
    real(RP) :: f2h1_UYZ_KEm2, f2h2_UYZ_KEm2
    real(RP) :: f2h1_UYZ_KSp2, f2h2_UYZ_KSp2
    real(RP) :: f2h1_UYZ_KEm3, f2h2_UYZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_UYZ_k,f2h2_UYZ_k,f2h1_UYZ_KS,f2h2_UYZ_KS) &
    !$omp private(f2h1_UYZ_KEm1,f2h2_UYZ_KEm1,f2h1_UYZ_KSp1,f2h2_UYZ_KSp1) &
    !$omp private(f2h1_UYZ_KEm2,f2h2_UYZ_KEm2,f2h1_UYZ_KSp2,f2h2_UYZ_KSp2) &
    !$omp private(f2h1_UYZ_KEm3,f2h2_UYZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J13G,MAPF) &
    !$omp shared(GSQRT,CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J13G, MAPF, CDZ)



    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
       f2h1_UYZ_k = F2H(k,I_UYZ)
       f2h2_UYZ_k = 1.0_RP - f2h1_UYZ_k
       vel = ( f2h1_UYZ_k * mom(k+1,i,j) &
             + f2h2_UYZ_k * mom(k,i,j) ) &
           / ( f2h1_UYZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i+1,j) ) &
             + f2h2_UYZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i+1,j) ) )
       vel = vel * J13G(k,i,j)
       flux(k,i,j) = vel / MAPF(i,j,+2) &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_UYZ_KS = F2H(KS,I_UYZ)
       f2h2_UYZ_KS = 1.0_RP - f2h1_UYZ_KS
       vel = ( f2h1_UYZ_KS * mom(KS+1,i,j) &
             + f2h2_UYZ_KS * mom(KS,i,j) ) &
           / ( f2h1_UYZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) &
             + f2h2_UYZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i+1,j) ) )
       vel = vel * J13G(KS,i,j)
       flux(KS,i,j) = vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm1 = F2H(KE-1,I_UYZ)
       f2h2_UYZ_KEm1 = 1.0_RP - f2h1_UYZ_KEm1
       vel = ( f2h1_UYZ_KEm1 * mom(KE,i,j) &
             + f2h2_UYZ_KEm1 * mom(KE-1,i,j) ) &
           / ( f2h1_UYZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i+1,j) ) &
             + f2h2_UYZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) )
       vel = vel * J13G(KE-1,i,j)
       flux(KE-1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) )

       f2h1_UYZ_KSp1 = F2H(KS+1,I_UYZ)
       f2h2_UYZ_KSp1 = 1.0_RP - f2h1_UYZ_KSp1
       vel = ( f2h1_UYZ_KSp1 * mom(KS+2,i,j) &
             + f2h2_UYZ_KSp1 * mom(KS+1,i,j) ) &
           / ( f2h1_UYZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) &
             + f2h2_UYZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) )
       vel = vel * J13G(KS+1,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm2 = F2H(KE-2,I_UYZ)
       f2h2_UYZ_KEm2 = 1.0_RP - f2h1_UYZ_KEm2
       vel = ( f2h1_UYZ_KEm2 * mom(KE-1,i,j) &
             + f2h2_UYZ_KEm2 * mom(KE-2,i,j) ) &
           / ( f2h1_UYZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) &
             + f2h2_UYZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) )
       vel = vel * J13G(KE-2,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) )

       f2h1_UYZ_KSp2 = F2H(KS+2,I_UYZ)
       f2h2_UYZ_KSp2 = 1.0_RP - f2h1_UYZ_KSp2
       vel = ( f2h1_UYZ_KSp2 * mom(KS+3,i,j) &
             + f2h2_UYZ_KSp2 * mom(KS+2,i,j) ) &
           / ( f2h1_UYZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i+1,j) ) &
             + f2h2_UYZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) )
       vel = vel * J13G(KS+2,i,j)
       flux(KS+2,i,j) = vel / MAPF(i,j,+2) &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm3 = F2H(KE-3,I_UYZ)
       f2h2_UYZ_KEm3 = 1.0_RP - f2h1_UYZ_KEm3
       vel = ( f2h1_UYZ_KEm3 * mom(KE-2,i,j) &
             + f2h2_UYZ_KEm3 * mom(KE-3,i,j) ) &
           / ( f2h1_UYZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) &
             + f2h2_UYZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i+1,j) ) )
       vel = vel * J13G(KE-3,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+2) &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) )

       flux(KE  ,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait



    !$acc end data

    !$omp end parallel
    return
  end subroutine ATMOS_DYN_FVM_fluxJ13_UYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation J23-flux at UYZ
  subroutine ATMOS_DYN_FVM_fluxJ23_UYZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J23G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J23G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XYZ_k, f2h2_XYZ_k
    real(RP) :: f2h1_XYZ_KS, f2h2_XYZ_KS
    real(RP) :: f2h1_XYZ_KEm1, f2h2_XYZ_KEm1
    real(RP) :: f2h1_XYZ_KSp1, f2h2_XYZ_KSp1
    real(RP) :: f2h1_XYZ_KEm2, f2h2_XYZ_KEm2
    real(RP) :: f2h1_XYZ_KSp2, f2h2_XYZ_KSp2
    real(RP) :: f2h1_XYZ_KEm3, f2h2_XYZ_KEm3
    real(RP) :: f2h1_UYZ_k, f2h2_UYZ_k
    real(RP) :: f2h1_UYZ_KS, f2h2_UYZ_KS
    real(RP) :: f2h1_UYZ_KEm1, f2h2_UYZ_KEm1
    real(RP) :: f2h1_UYZ_KSp1, f2h2_UYZ_KSp1
    real(RP) :: f2h1_UYZ_KEm2, f2h2_UYZ_KEm2
    real(RP) :: f2h1_UYZ_KSp2, f2h2_UYZ_KSp2
    real(RP) :: f2h1_UYZ_KEm3, f2h2_UYZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XYZ_k,f2h2_XYZ_k,f2h1_XYZ_KS,f2h2_XYZ_KS) &
    !$omp private(f2h1_XYZ_KEm1,f2h2_XYZ_KEm1,f2h1_XYZ_KSp1,f2h2_XYZ_KSp1) &
    !$omp private(f2h1_XYZ_KEm2,f2h2_XYZ_KEm2,f2h1_XYZ_KSp2,f2h2_XYZ_KSp2) &
    !$omp private(f2h1_XYZ_KEm3,f2h2_XYZ_KEm3,f2h1_UYZ_k,f2h2_UYZ_k) &
    !$omp private(f2h1_UYZ_KS,f2h2_UYZ_KS,f2h1_UYZ_KEm1,f2h2_UYZ_KEm1) &
    !$omp private(f2h1_UYZ_KSp1,f2h2_UYZ_KSp1,f2h1_UYZ_KEm2,f2h2_UYZ_KEm2) &
    !$omp private(f2h1_UYZ_KSp2,f2h2_UYZ_KSp2,f2h1_UYZ_KEm3,f2h2_UYZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J23G,MAPF) &
    !$omp shared(GSQRT,CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J23G, MAPF, CDZ)


    if ( TwoD ) then

    !$omp do OMP_SCHEDULE_
    !$acc kernels
    do j = JJS, JJE
    do k = KS+3, KE-4
       i = IIS
       f2h1_XYZ_k = F2H(k,I_XYZ)
       f2h2_XYZ_k = 1.0_RP - f2h1_XYZ_k
       vel = ( f2h1_XYZ_k * 0.5_RP * ( mom(k+1,i,j)+mom(k+1,i,j-1) ) &
             + f2h2_XYZ_k * 0.5_RP * ( mom(k,i,j)+mom(k,i,j-1) ) ) &
           / ( f2h1_XYZ_k * DENS(k+1,i,j) &
             + f2h2_XYZ_k * DENS(k,i,j) )
       vel = vel * J23G(k,i,j)
       flux(k,i,j) = vel * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) )
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_
    !$acc kernels
    do j = JJS, JJE
       i = IIS
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_XYZ_KS = F2H(KS,I_XYZ)
       f2h2_XYZ_KS = 1.0_RP - f2h1_XYZ_KS
       vel = ( f2h1_XYZ_KS * 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i,j-1) ) &
             + f2h2_XYZ_KS * 0.5_RP * ( mom(KS,i,j)+mom(KS,i,j-1) ) ) &
           / ( f2h1_XYZ_KS * DENS(KS+1,i,j) &
             + f2h2_XYZ_KS * DENS(KS,i,j) )
       vel = vel * J23G(KS,i,j)
       flux(KS,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) )

       f2h1_XYZ_KEm1 = F2H(KE-1,I_XYZ)
       f2h2_XYZ_KEm1 = 1.0_RP - f2h1_XYZ_KEm1
       vel = ( f2h1_XYZ_KEm1 * 0.5_RP * ( mom(KE,i,j)+mom(KE,i,j-1) ) &
             + f2h2_XYZ_KEm1 * 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i,j-1) ) ) &
           / ( f2h1_XYZ_KEm1 * DENS(KE,i,j) &
             + f2h2_XYZ_KEm1 * DENS(KE-1,i,j) )
       vel = vel * J23G(KE-1,i,j)
       flux(KE-1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) )

       f2h1_XYZ_KSp1 = F2H(KS+1,I_XYZ)
       f2h2_XYZ_KSp1 = 1.0_RP - f2h1_XYZ_KSp1
       vel = ( f2h1_XYZ_KSp1 * 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i,j-1) ) &
             + f2h2_XYZ_KSp1 * 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i,j-1) ) ) &
           / ( f2h1_XYZ_KSp1 * DENS(KS+2,i,j) &
             + f2h2_XYZ_KSp1 * DENS(KS+1,i,j) )
       vel = vel * J23G(KS+1,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) )

       f2h1_XYZ_KEm2 = F2H(KE-2,I_XYZ)
       f2h2_XYZ_KEm2 = 1.0_RP - f2h1_XYZ_KEm2
       vel = ( f2h1_XYZ_KEm2 * 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i,j-1) ) &
             + f2h2_XYZ_KEm2 * 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i,j-1) ) ) &
           / ( f2h1_XYZ_KEm2 * DENS(KE-1,i,j) &
             + f2h2_XYZ_KEm2 * DENS(KE-2,i,j) )
       vel = vel * J23G(KE-2,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) )

       f2h1_XYZ_KSp2 = F2H(KS+2,I_XYZ)
       f2h2_XYZ_KSp2 = 1.0_RP - f2h1_XYZ_KSp2
       vel = ( f2h1_XYZ_KSp2 * 0.5_RP * ( mom(KS+3,i,j)+mom(KS+3,i,j-1) ) &
             + f2h2_XYZ_KSp2 * 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i,j-1) ) ) &
           / ( f2h1_XYZ_KSp2 * DENS(KS+3,i,j) &
             + f2h2_XYZ_KSp2 * DENS(KS+2,i,j) )
       vel = vel * J23G(KS+2,i,j)
       flux(KS+2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) )

       f2h1_XYZ_KEm3 = F2H(KE-3,I_XYZ)
       f2h2_XYZ_KEm3 = 1.0_RP - f2h1_XYZ_KEm3
       vel = ( f2h1_XYZ_KEm3 * 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i,j-1) ) &
             + f2h2_XYZ_KEm3 * 0.5_RP * ( mom(KE-3,i,j)+mom(KE-3,i,j-1) ) ) &
           / ( f2h1_XYZ_KEm3 * DENS(KE-2,i,j) &
             + f2h2_XYZ_KEm3 * DENS(KE-3,i,j) )
       vel = vel * J23G(KE-3,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) )

       flux(KE  ,i,j) = 0.0_RP
    enddo
    !$acc end kernels
    !$omp end do nowait

    else


    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
       f2h1_UYZ_k = F2H(k,I_UYZ)
       f2h2_UYZ_k = 1.0_RP - f2h1_UYZ_k
       vel = ( f2h1_UYZ_k * 0.25_RP * ( mom(k+1,i,j)+mom(k+1,i+1,j)+mom(k+1,i,j-1)+mom(k+1,i+1,j-1) ) &
             + f2h2_UYZ_k * 0.25_RP * ( mom(k,i,j)+mom(k,i+1,j)+mom(k,i,j-1)+mom(k,i+1,j-1) ) ) &
           / ( f2h1_UYZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i+1,j) ) &
             + f2h2_UYZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i+1,j) ) )
       vel = vel * J23G(k,i,j)
       flux(k,i,j) = vel / MAPF(i,j,+1) &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_UYZ_KS = F2H(KS,I_UYZ)
       f2h2_UYZ_KS = 1.0_RP - f2h1_UYZ_KS
       vel = ( f2h1_UYZ_KS * 0.25_RP * ( mom(KS+1,i,j)+mom(KS+1,i+1,j)+mom(KS+1,i,j-1)+mom(KS+1,i+1,j-1) ) &
             + f2h2_UYZ_KS * 0.25_RP * ( mom(KS,i,j)+mom(KS,i+1,j)+mom(KS,i,j-1)+mom(KS,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) &
             + f2h2_UYZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i+1,j) ) )
       vel = vel * J23G(KS,i,j)
       flux(KS,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm1 = F2H(KE-1,I_UYZ)
       f2h2_UYZ_KEm1 = 1.0_RP - f2h1_UYZ_KEm1
       vel = ( f2h1_UYZ_KEm1 * 0.25_RP * ( mom(KE,i,j)+mom(KE,i+1,j)+mom(KE,i,j-1)+mom(KE,i+1,j-1) ) &
             + f2h2_UYZ_KEm1 * 0.25_RP * ( mom(KE-1,i,j)+mom(KE-1,i+1,j)+mom(KE-1,i,j-1)+mom(KE-1,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i+1,j) ) &
             + f2h2_UYZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) )
       vel = vel * J23G(KE-1,i,j)
       flux(KE-1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) )

       f2h1_UYZ_KSp1 = F2H(KS+1,I_UYZ)
       f2h2_UYZ_KSp1 = 1.0_RP - f2h1_UYZ_KSp1
       vel = ( f2h1_UYZ_KSp1 * 0.25_RP * ( mom(KS+2,i,j)+mom(KS+2,i+1,j)+mom(KS+2,i,j-1)+mom(KS+2,i+1,j-1) ) &
             + f2h2_UYZ_KSp1 * 0.25_RP * ( mom(KS+1,i,j)+mom(KS+1,i+1,j)+mom(KS+1,i,j-1)+mom(KS+1,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) &
             + f2h2_UYZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i+1,j) ) )
       vel = vel * J23G(KS+1,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm2 = F2H(KE-2,I_UYZ)
       f2h2_UYZ_KEm2 = 1.0_RP - f2h1_UYZ_KEm2
       vel = ( f2h1_UYZ_KEm2 * 0.25_RP * ( mom(KE-1,i,j)+mom(KE-1,i+1,j)+mom(KE-1,i,j-1)+mom(KE-1,i+1,j-1) ) &
             + f2h2_UYZ_KEm2 * 0.25_RP * ( mom(KE-2,i,j)+mom(KE-2,i+1,j)+mom(KE-2,i,j-1)+mom(KE-2,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i+1,j) ) &
             + f2h2_UYZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) )
       vel = vel * J23G(KE-2,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) )

       f2h1_UYZ_KSp2 = F2H(KS+2,I_UYZ)
       f2h2_UYZ_KSp2 = 1.0_RP - f2h1_UYZ_KSp2
       vel = ( f2h1_UYZ_KSp2 * 0.25_RP * ( mom(KS+3,i,j)+mom(KS+3,i+1,j)+mom(KS+3,i,j-1)+mom(KS+3,i+1,j-1) ) &
             + f2h2_UYZ_KSp2 * 0.25_RP * ( mom(KS+2,i,j)+mom(KS+2,i+1,j)+mom(KS+2,i,j-1)+mom(KS+2,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i+1,j) ) &
             + f2h2_UYZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i+1,j) ) )
       vel = vel * J23G(KS+2,i,j)
       flux(KS+2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) )

       f2h1_UYZ_KEm3 = F2H(KE-3,I_UYZ)
       f2h2_UYZ_KEm3 = 1.0_RP - f2h1_UYZ_KEm3
       vel = ( f2h1_UYZ_KEm3 * 0.25_RP * ( mom(KE-2,i,j)+mom(KE-2,i+1,j)+mom(KE-2,i,j-1)+mom(KE-2,i+1,j-1) ) &
             + f2h2_UYZ_KEm3 * 0.25_RP * ( mom(KE-3,i,j)+mom(KE-3,i+1,j)+mom(KE-3,i,j-1)+mom(KE-3,i+1,j-1) ) ) &
           / ( f2h1_UYZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i+1,j) ) &
             + f2h2_UYZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i+1,j) ) )
       vel = vel * J23G(KE-3,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) )

       flux(KE  ,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait


    end if


    !$acc end data

    !$omp end parallel
    return
  end subroutine ATMOS_DYN_FVM_fluxJ23_UYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation X-flux at UY
  subroutine ATMOS_DYN_FVM_fluxX_UYZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    ! note that x-index is added by -1



    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE+1
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i  ,j) )
       call CHECK( __LINE__, mom(k,i-1,j) )

       call CHECK( __LINE__, val(k,i-1,j) )
       call CHECK( __LINE__, val(k,i,j) )

       call CHECK( __LINE__, val(k,i-2,j) )
       call CHECK( __LINE__, val(k,i+1,j) )

       call CHECK( __LINE__, val(k,i-3,j) )
       call CHECK( __LINE__, val(k,i+2,j) )

       call CHECK( __LINE__, val(k,i-4,j) )
       call CHECK( __LINE__, val(k,i+3,j) )

#endif
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i-1,j) ) ) &
           / ( DENS(k,i,j) )
       flux(k,i-1,j) = GSQRT(k,i,j) / MAPF(i,j,+2) * vel &
                   * ( F81 * ( val(k,i,j)+val(k,i-1,j) ) &
                     + F82 * ( val(k,i+1,j)+val(k,i-2,j) ) &
                     + F83 * ( val(k,i+2,j)+val(k,i-3,j) ) &
                     + F84 * ( val(k,i+3,j)+val(k,i-4,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif



    return
  end subroutine ATMOS_DYN_FVM_fluxX_UYZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation Y-flux at UY
  subroutine ATMOS_DYN_FVM_fluxY_UYZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------



    if ( TwoD ) then

    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff,TwoD)
    !$acc kernels
    do j = JJS-1, JJE
    do k = KS, KE
       i = IIS
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i  ,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j-1) )
       call CHECK( __LINE__, val(k,i,j+2) )

       call CHECK( __LINE__, val(k,i,j-2) )
       call CHECK( __LINE__, val(k,i,j+3) )

       call CHECK( __LINE__, val(k,i,j-3) )
       call CHECK( __LINE__, val(k,i,j+4) )

#endif
       vel = ( mom(k,i,j) ) &
           / ( 0.5_RP * ( DENS(k,i,j)+DENS(k,i,j+1) ) )
       flux(k,i,j) = GSQRT(k,i,j) / MAPF(i,j,+1) * vel &
                   * ( F81 * ( val(k,i,j+1)+val(k,i,j) ) &
                     + F82 * ( val(k,i,j+2)+val(k,i,j-1) ) &
                     + F83 * ( val(k,i,j+3)+val(k,i,j-2) ) &
                     + F84 * ( val(k,i,j+4)+val(k,i,j-3) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    else


    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff)
    !$acc kernels
    do j = JJS-1, JJE
    do i = IIS, IIE
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i  ,j) )
       call CHECK( __LINE__, mom(k,i-1,j) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j-1) )
       call CHECK( __LINE__, val(k,i,j+2) )

       call CHECK( __LINE__, val(k,i,j-2) )
       call CHECK( __LINE__, val(k,i,j+3) )

       call CHECK( __LINE__, val(k,i,j-3) )
       call CHECK( __LINE__, val(k,i,j+4) )

#endif
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i+1,j) ) ) &
           / ( 0.25_RP * ( DENS(k,i,j)+DENS(k,i+1,j)+DENS(k,i,j+1)+DENS(k,i+1,j+1) ) )
       flux(k,i,j) = GSQRT(k,i,j) / MAPF(i,j,+1) * vel &
                   * ( F81 * ( val(k,i,j+1)+val(k,i,j) ) &
                     + F82 * ( val(k,i,j+2)+val(k,i,j-1) ) &
                     + F83 * ( val(k,i,j+3)+val(k,i,j-2) ) &
                     + F84 * ( val(k,i,j+4)+val(k,i,j-3) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif


    end if


    return
  end subroutine ATMOS_DYN_FVM_fluxY_UYZ_cd8



  !-----------------------------------------------------------------------------
  !> calculation z-flux at XV
  subroutine ATMOS_DYN_FVM_fluxZ_XVZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J33G,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J33G
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XVZ_k, f2h2_XVZ_k
    real(RP) :: f2h1_XVZ_KS, f2h2_XVZ_KS
    real(RP) :: f2h1_XVZ_KEm1, f2h2_XVZ_KEm1
    real(RP) :: f2h1_XVZ_KSp1, f2h2_XVZ_KSp1
    real(RP) :: f2h1_XVZ_KEm2, f2h2_XVZ_KEm2
    real(RP) :: f2h1_XVZ_KSp2, f2h2_XVZ_KSp2
    real(RP) :: f2h1_XVZ_KEm3, f2h2_XVZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XVZ_k,f2h2_XVZ_k,f2h1_XVZ_KS,f2h2_XVZ_KS) &
    !$omp private(f2h1_XVZ_KEm1,f2h2_XVZ_KEm1,f2h1_XVZ_KSp1,f2h2_XVZ_KSp1) &
    !$omp private(f2h1_XVZ_KEm2,f2h2_XVZ_KEm2,f2h1_XVZ_KSp2,f2h2_XVZ_KSp2) &
    !$omp private(f2h1_XVZ_KEm3,f2h2_XVZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J33G,GSQRT,num_diff) &
    !$omp shared(CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, num_diff, CDZ)


    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i,j) )
       call CHECK( __LINE__, mom(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k+1,i,j) )

       call CHECK( __LINE__, val(k-1,i,j) )
       call CHECK( __LINE__, val(k+2,i,j) )

       call CHECK( __LINE__, val(k-2,i,j) )
       call CHECK( __LINE__, val(k+3,i,j) )

       call CHECK( __LINE__, val(k-3,i,j) )
       call CHECK( __LINE__, val(k+4,i,j) )

#endif
       f2h1_XVZ_k = F2H(k,I_XVZ)
       f2h2_XVZ_k = 1.0_RP - f2h1_XVZ_k
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i,j+1) ) ) &
           / ( f2h1_XVZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i,j+1) ) &
             + f2h2_XVZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i,j+1) ) )
       flux(k,i,j) = J33G * vel &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
#ifdef DEBUG

       call CHECK( __LINE__, mom(KS,i  ,j) )
       call CHECK( __LINE__, mom(KS,i,j+1) )
       call CHECK( __LINE__, val(KS+1,i,j) )
       call CHECK( __LINE__, val(KS,i,j) )

       call CHECK( __LINE__, mom(KS+1,i  ,j) )
       call CHECK( __LINE__, mom(KS+1,i,j+1) )
       call CHECK( __LINE__, val(KS+3,i,j) )
       call CHECK( __LINE__, val(KS+2,i,j) )

       call CHECK( __LINE__, mom(KS+2,i  ,j) )
       call CHECK( __LINE__, mom(KS+2,i,j+1) )
       call CHECK( __LINE__, val(KS+5,i,j) )
       call CHECK( __LINE__, val(KS+4,i,j) )

#endif
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_XVZ_KS = F2H(KS,I_XVZ)
       f2h2_XVZ_KS = 1.0_RP - f2h1_XVZ_KS
       vel = ( 0.5_RP * ( mom(KS,i,j)+mom(KS,i,j+1) ) ) &
           / ( f2h1_XVZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) &
             + f2h2_XVZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i,j+1) ) )
       flux(KS,i,j) = J33G * vel &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS,i,j) * num_diff(KS,i,j)
       f2h1_XVZ_KEm1 = F2H(KE-1,I_XVZ)
       f2h2_XVZ_KEm1 = 1.0_RP - f2h1_XVZ_KEm1
       vel = ( 0.5_RP * ( mom(KE-1,i,j)+mom(KE-1,i,j+1) ) ) &
           / ( f2h1_XVZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i,j+1) ) &
             + f2h2_XVZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) )
       flux(KE-1,i,j) = J33G * vel &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) ) &
                   + GSQRT(KE-1,i,j) * num_diff(KE-1,i,j)

       f2h1_XVZ_KSp1 = F2H(KS+1,I_XVZ)
       f2h2_XVZ_KSp1 = 1.0_RP - f2h1_XVZ_KSp1
       vel = ( 0.5_RP * ( mom(KS+1,i,j)+mom(KS+1,i,j+1) ) ) &
           / ( f2h1_XVZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) &
             + f2h2_XVZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) )
       flux(KS+1,i,j) = J33G * vel &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+1,i,j) * num_diff(KS+1,i,j)
       f2h1_XVZ_KEm2 = F2H(KE-2,I_XVZ)
       f2h2_XVZ_KEm2 = 1.0_RP - f2h1_XVZ_KEm2
       vel = ( 0.5_RP * ( mom(KE-2,i,j)+mom(KE-2,i,j+1) ) ) &
           / ( f2h1_XVZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) &
             + f2h2_XVZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) )
       flux(KE-2,i,j) = J33G * vel &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) ) &
                   + GSQRT(KE-2,i,j) * num_diff(KE-2,i,j)

       f2h1_XVZ_KSp2 = F2H(KS+2,I_XVZ)
       f2h2_XVZ_KSp2 = 1.0_RP - f2h1_XVZ_KSp2
       vel = ( 0.5_RP * ( mom(KS+2,i,j)+mom(KS+2,i,j+1) ) ) &
           / ( f2h1_XVZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i,j+1) ) &
             + f2h2_XVZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) )
       flux(KS+2,i,j) = J33G * vel &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) ) &
                   + GSQRT(KS+2,i,j) * num_diff(KS+2,i,j)
       f2h1_XVZ_KEm3 = F2H(KE-3,I_XVZ)
       f2h2_XVZ_KEm3 = 1.0_RP - f2h1_XVZ_KEm3
       vel = ( 0.5_RP * ( mom(KE-3,i,j)+mom(KE-3,i,j+1) ) ) &
           / ( f2h1_XVZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) &
             + f2h2_XVZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i,j+1) ) )
       flux(KE-3,i,j) = J33G * vel &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) ) &
                   + GSQRT(KE-3,i,j) * num_diff(KE-3,i,j)

       flux(KE,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait


    !$acc end data

    !$omp end parallel
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif

    return
  end subroutine ATMOS_DYN_FVM_fluxZ_XVZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation J13-flux at XVZ
  subroutine ATMOS_DYN_FVM_fluxJ13_XVZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J13G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J13G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XVZ_k, f2h2_XVZ_k
    real(RP) :: f2h1_XVZ_KS, f2h2_XVZ_KS
    real(RP) :: f2h1_XVZ_KEm1, f2h2_XVZ_KEm1
    real(RP) :: f2h1_XVZ_KSp1, f2h2_XVZ_KSp1
    real(RP) :: f2h1_XVZ_KEm2, f2h2_XVZ_KEm2
    real(RP) :: f2h1_XVZ_KSp2, f2h2_XVZ_KSp2
    real(RP) :: f2h1_XVZ_KEm3, f2h2_XVZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XVZ_k,f2h2_XVZ_k,f2h1_XVZ_KS,f2h2_XVZ_KS) &
    !$omp private(f2h1_XVZ_KEm1,f2h2_XVZ_KEm1,f2h1_XVZ_KSp1,f2h2_XVZ_KSp1) &
    !$omp private(f2h1_XVZ_KEm2,f2h2_XVZ_KEm2,f2h1_XVZ_KSp2,f2h2_XVZ_KSp2) &
    !$omp private(f2h1_XVZ_KEm3,f2h2_XVZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J13G,MAPF) &
    !$omp shared(GSQRT,CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J13G, MAPF, CDZ)



    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
       f2h1_XVZ_k = F2H(k,I_XVZ)
       f2h2_XVZ_k = 1.0_RP - f2h1_XVZ_k
       vel = ( f2h1_XVZ_k * 0.25_RP * ( mom(k+1,i,j)+mom(k+1,i-1,j)+mom(k+1,i,j+1)+mom(k+1,i-1,j+1) ) &
             + f2h2_XVZ_k * 0.25_RP * ( mom(k,i,j)+mom(k,i-1,j)+mom(k,i,j+1)+mom(k,i-1,j+1) ) ) &
           / ( f2h1_XVZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i,j+1) ) &
             + f2h2_XVZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i,j+1) ) )
       vel = vel * J13G(k,i,j)
       flux(k,i,j) = vel / MAPF(i,j,+2) &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_XVZ_KS = F2H(KS,I_XVZ)
       f2h2_XVZ_KS = 1.0_RP - f2h1_XVZ_KS
       vel = ( f2h1_XVZ_KS * 0.25_RP * ( mom(KS+1,i,j)+mom(KS+1,i-1,j)+mom(KS+1,i,j+1)+mom(KS+1,i-1,j+1) ) &
             + f2h2_XVZ_KS * 0.25_RP * ( mom(KS,i,j)+mom(KS,i-1,j)+mom(KS,i,j+1)+mom(KS,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) &
             + f2h2_XVZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i,j+1) ) )
       vel = vel * J13G(KS,i,j)
       flux(KS,i,j) = vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm1 = F2H(KE-1,I_XVZ)
       f2h2_XVZ_KEm1 = 1.0_RP - f2h1_XVZ_KEm1
       vel = ( f2h1_XVZ_KEm1 * 0.25_RP * ( mom(KE,i,j)+mom(KE,i-1,j)+mom(KE,i,j+1)+mom(KE,i-1,j+1) ) &
             + f2h2_XVZ_KEm1 * 0.25_RP * ( mom(KE-1,i,j)+mom(KE-1,i-1,j)+mom(KE-1,i,j+1)+mom(KE-1,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i,j+1) ) &
             + f2h2_XVZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) )
       vel = vel * J13G(KE-1,i,j)
       flux(KE-1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) )

       f2h1_XVZ_KSp1 = F2H(KS+1,I_XVZ)
       f2h2_XVZ_KSp1 = 1.0_RP - f2h1_XVZ_KSp1
       vel = ( f2h1_XVZ_KSp1 * 0.25_RP * ( mom(KS+2,i,j)+mom(KS+2,i-1,j)+mom(KS+2,i,j+1)+mom(KS+2,i-1,j+1) ) &
             + f2h2_XVZ_KSp1 * 0.25_RP * ( mom(KS+1,i,j)+mom(KS+1,i-1,j)+mom(KS+1,i,j+1)+mom(KS+1,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) &
             + f2h2_XVZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) )
       vel = vel * J13G(KS+1,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm2 = F2H(KE-2,I_XVZ)
       f2h2_XVZ_KEm2 = 1.0_RP - f2h1_XVZ_KEm2
       vel = ( f2h1_XVZ_KEm2 * 0.25_RP * ( mom(KE-1,i,j)+mom(KE-1,i-1,j)+mom(KE-1,i,j+1)+mom(KE-1,i-1,j+1) ) &
             + f2h2_XVZ_KEm2 * 0.25_RP * ( mom(KE-2,i,j)+mom(KE-2,i-1,j)+mom(KE-2,i,j+1)+mom(KE-2,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) &
             + f2h2_XVZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) )
       vel = vel * J13G(KE-2,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+2) &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) )

       f2h1_XVZ_KSp2 = F2H(KS+2,I_XVZ)
       f2h2_XVZ_KSp2 = 1.0_RP - f2h1_XVZ_KSp2
       vel = ( f2h1_XVZ_KSp2 * 0.25_RP * ( mom(KS+3,i,j)+mom(KS+3,i-1,j)+mom(KS+3,i,j+1)+mom(KS+3,i-1,j+1) ) &
             + f2h2_XVZ_KSp2 * 0.25_RP * ( mom(KS+2,i,j)+mom(KS+2,i-1,j)+mom(KS+2,i,j+1)+mom(KS+2,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i,j+1) ) &
             + f2h2_XVZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) )
       vel = vel * J13G(KS+2,i,j)
       flux(KS+2,i,j) = vel / MAPF(i,j,+2) &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm3 = F2H(KE-3,I_XVZ)
       f2h2_XVZ_KEm3 = 1.0_RP - f2h1_XVZ_KEm3
       vel = ( f2h1_XVZ_KEm3 * 0.25_RP * ( mom(KE-2,i,j)+mom(KE-2,i-1,j)+mom(KE-2,i,j+1)+mom(KE-2,i-1,j+1) ) &
             + f2h2_XVZ_KEm3 * 0.25_RP * ( mom(KE-3,i,j)+mom(KE-3,i-1,j)+mom(KE-3,i,j+1)+mom(KE-3,i-1,j+1) ) ) &
           / ( f2h1_XVZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) &
             + f2h2_XVZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i,j+1) ) )
       vel = vel * J13G(KE-3,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+2) &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) )

       flux(KE  ,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait



    !$acc end data

    !$omp end parallel
    return
  end subroutine ATMOS_DYN_FVM_fluxJ13_XVZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation J23-flux at XVZ
  subroutine ATMOS_DYN_FVM_fluxJ23_XVZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, J23G, MAPF, &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: J23G    (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    real(RP) :: f2h1_XVZ_k, f2h2_XVZ_k
    real(RP) :: f2h1_XVZ_KS, f2h2_XVZ_KS
    real(RP) :: f2h1_XVZ_KEm1, f2h2_XVZ_KEm1
    real(RP) :: f2h1_XVZ_KSp1, f2h2_XVZ_KSp1
    real(RP) :: f2h1_XVZ_KEm2, f2h2_XVZ_KEm2
    real(RP) :: f2h1_XVZ_KSp2, f2h2_XVZ_KSp2
    real(RP) :: f2h1_XVZ_KEm3, f2h2_XVZ_KEm3
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    !$omp parallel default(none) private(i,j,k,vel) &
    !$omp private(f2h1_XVZ_k,f2h2_XVZ_k,f2h1_XVZ_KS,f2h2_XVZ_KS) &
    !$omp private(f2h1_XVZ_KEm1,f2h2_XVZ_KEm1,f2h1_XVZ_KSp1,f2h2_XVZ_KSp1) &
    !$omp private(f2h1_XVZ_KEm2,f2h2_XVZ_KEm2,f2h1_XVZ_KSp2,f2h2_XVZ_KSp2) &
    !$omp private(f2h1_XVZ_KEm3,f2h2_XVZ_KEm3) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,J23G,MAPF) &
    !$omp shared(GSQRT,CDZ,TwoD)

    !$acc data copy(flux) copyin(mom, val, DENS, GSQRT, J23G, MAPF, CDZ)



    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
    do k = KS+3, KE-4
       f2h1_XVZ_k = F2H(k,I_XVZ)
       f2h2_XVZ_k = 1.0_RP - f2h1_XVZ_k
       vel = ( f2h1_XVZ_k * mom(k+1,i,j) &
             + f2h2_XVZ_k * mom(k,i,j) ) &
           / ( f2h1_XVZ_k * 0.5_RP * ( DENS(k+1,i,j)+DENS(k+1,i,j+1) ) &
             + f2h2_XVZ_k * 0.5_RP * ( DENS(k,i,j)+DENS(k,i,j+1) ) )
       vel = vel * J23G(k,i,j)
       flux(k,i,j) = vel / MAPF(i,j,+1) &
                   * ( F81 * ( val(k+1,i,j)+val(k,i,j) ) &
                     + F82 * ( val(k+2,i,j)+val(k-1,i,j) ) &
                     + F83 * ( val(k+3,i,j)+val(k-2,i,j) ) &
                     + F84 * ( val(k+4,i,j)+val(k-3,i,j) ) )
    enddo
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait

    !$omp do OMP_SCHEDULE_ collapse(2)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS, IIE
       ! The boundary condition is qflx_hi + qflxJ13 + qfluxJ23 = 0 at KS-1.
       ! The flux at KS-1 can be non-zero.
       ! To reduce calculations, all the fluxes are set to zero.
       flux(KS-1,i,j) = 0.0_RP

       f2h1_XVZ_KS = F2H(KS,I_XVZ)
       f2h2_XVZ_KS = 1.0_RP - f2h1_XVZ_KS
       vel = ( f2h1_XVZ_KS * mom(KS+1,i,j) &
             + f2h2_XVZ_KS * mom(KS,i,j) ) &
           / ( f2h1_XVZ_KS * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) &
             + f2h2_XVZ_KS * 0.5_RP * ( DENS(KS,i,j)+DENS(KS,i,j+1) ) )
       vel = vel * J23G(KS,i,j)
       flux(KS,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KS+1,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm1 = F2H(KE-1,I_XVZ)
       f2h2_XVZ_KEm1 = 1.0_RP - f2h1_XVZ_KEm1
       vel = ( f2h1_XVZ_KEm1 * mom(KE,i,j) &
             + f2h2_XVZ_KEm1 * mom(KE-1,i,j) ) &
           / ( f2h1_XVZ_KEm1 * 0.5_RP * ( DENS(KE,i,j)+DENS(KE,i,j+1) ) &
             + f2h2_XVZ_KEm1 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) )
       vel = vel * J23G(KE-1,i,j)
       flux(KE-1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F2 * ( val(KE,i,j)+val(KE-1,i,j) ) )

       f2h1_XVZ_KSp1 = F2H(KS+1,I_XVZ)
       f2h2_XVZ_KSp1 = 1.0_RP - f2h1_XVZ_KSp1
       vel = ( f2h1_XVZ_KSp1 * mom(KS+2,i,j) &
             + f2h2_XVZ_KSp1 * mom(KS+1,i,j) ) &
           / ( f2h1_XVZ_KSp1 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) &
             + f2h2_XVZ_KSp1 * 0.5_RP * ( DENS(KS+1,i,j)+DENS(KS+1,i,j+1) ) )
       vel = vel * J23G(KS+1,i,j)
       flux(KS+1,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KS+2,i,j)+val(KS+1,i,j) ) &
                     + F42 * ( val(KS+3,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm2 = F2H(KE-2,I_XVZ)
       f2h2_XVZ_KEm2 = 1.0_RP - f2h1_XVZ_KEm2
       vel = ( f2h1_XVZ_KEm2 * mom(KE-1,i,j) &
             + f2h2_XVZ_KEm2 * mom(KE-2,i,j) ) &
           / ( f2h1_XVZ_KEm2 * 0.5_RP * ( DENS(KE-1,i,j)+DENS(KE-1,i,j+1) ) &
             + f2h2_XVZ_KEm2 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) )
       vel = vel * J23G(KE-2,i,j)
       flux(KE-2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F41 * ( val(KE-1,i,j)+val(KE-2,i,j) ) &
                     + F42 * ( val(KE,i,j)+val(KE-3,i,j) ) )

       f2h1_XVZ_KSp2 = F2H(KS+2,I_XVZ)
       f2h2_XVZ_KSp2 = 1.0_RP - f2h1_XVZ_KSp2
       vel = ( f2h1_XVZ_KSp2 * mom(KS+3,i,j) &
             + f2h2_XVZ_KSp2 * mom(KS+2,i,j) ) &
           / ( f2h1_XVZ_KSp2 * 0.5_RP * ( DENS(KS+3,i,j)+DENS(KS+3,i,j+1) ) &
             + f2h2_XVZ_KSp2 * 0.5_RP * ( DENS(KS+2,i,j)+DENS(KS+2,i,j+1) ) )
       vel = vel * J23G(KS+2,i,j)
       flux(KS+2,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KS+3,i,j)+val(KS+2,i,j) ) &
                     + F62 * ( val(KS+4,i,j)+val(KS+1,i,j) ) &
                     + F63 * ( val(KS+5,i,j)+val(KS,i,j) ) )

       f2h1_XVZ_KEm3 = F2H(KE-3,I_XVZ)
       f2h2_XVZ_KEm3 = 1.0_RP - f2h1_XVZ_KEm3
       vel = ( f2h1_XVZ_KEm3 * mom(KE-2,i,j) &
             + f2h2_XVZ_KEm3 * mom(KE-3,i,j) ) &
           / ( f2h1_XVZ_KEm3 * 0.5_RP * ( DENS(KE-2,i,j)+DENS(KE-2,i,j+1) ) &
             + f2h2_XVZ_KEm3 * 0.5_RP * ( DENS(KE-3,i,j)+DENS(KE-3,i,j+1) ) )
       vel = vel * J23G(KE-3,i,j)
       flux(KE-3,i,j) = vel / MAPF(i,j,+1) &
                   * ( F61 * ( val(KE-2,i,j)+val(KE-3,i,j) ) &
                     + F62 * ( val(KE-1,i,j)+val(KE-4,i,j) ) &
                     + F63 * ( val(KE,i,j)+val(KE-5,i,j) ) )

       flux(KE  ,i,j) = 0.0_RP
    enddo
    enddo
    !$acc end kernels
    !$omp end do nowait



    !$acc end data

    !$omp end parallel
    return
  end subroutine ATMOS_DYN_FVM_fluxJ23_XVZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation X-flux at XV
  subroutine ATMOS_DYN_FVM_fluxX_XVZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------



    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff)
    !$acc kernels
    do j = JJS, JJE
    do i = IIS-1, IIE
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i  ,j) )
       call CHECK( __LINE__, mom(k,i,j-1) )

       call CHECK( __LINE__, val(k,i,j) )
       call CHECK( __LINE__, val(k,i+1,j) )

       call CHECK( __LINE__, val(k,i-1,j) )
       call CHECK( __LINE__, val(k,i+2,j) )

       call CHECK( __LINE__, val(k,i-2,j) )
       call CHECK( __LINE__, val(k,i+3,j) )

       call CHECK( __LINE__, val(k,i-3,j) )
       call CHECK( __LINE__, val(k,i+4,j) )

#endif
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i,j+1) ) ) &
           / ( 0.25_RP * ( DENS(k,i,j)+DENS(k,i+1,j)+DENS(k,i,j+1)+DENS(k,i+1,j+1) ) )
       flux(k,i,j) = GSQRT(k,i,j) / MAPF(i,j,+2) * vel &
                   * ( F81 * ( val(k,i+1,j)+val(k,i,j) ) &
                     + F82 * ( val(k,i+2,j)+val(k,i-1,j) ) &
                     + F83 * ( val(k,i+3,j)+val(k,i-2,j) ) &
                     + F84 * ( val(k,i+4,j)+val(k,i-3,j) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif



    return
  end subroutine ATMOS_DYN_FVM_fluxX_XVZ_cd8

  !-----------------------------------------------------------------------------
  !> calculation Y-flux at XV
  subroutine ATMOS_DYN_FVM_fluxY_XVZ_cd8( &
       flux,              &
       mom, val, DENS,    &
       GSQRT, MAPF,       &
       num_diff,          &
       CDZ, TwoD,         &
       IIS, IIE, JJS, JJE )
    implicit none

    real(RP), intent(inout) :: flux    (KA,IA,JA)
    real(RP), intent(in)  :: mom     (KA,IA,JA)
    real(RP), intent(in)  :: val     (KA,IA,JA)
    real(RP), intent(in)  :: DENS    (KA,IA,JA)
    real(RP), intent(in)  :: GSQRT   (KA,IA,JA)
    real(RP), intent(in)  :: MAPF    (   IA,JA,2)
    real(RP), intent(in)  :: num_diff(KA,IA,JA)
    real(RP), intent(in)  :: CDZ     (KA)
    logical,  intent(in)  :: TwoD
    integer,  intent(in)  :: IIS, IIE, JJS, JJE

    real(RP) :: vel
    integer  :: k, i, j
    !---------------------------------------------------------------------------

    ! note that y-index is added by -1



    !$omp parallel do default(none) private(i,j,k) OMP_SCHEDULE_ collapse(2) &
    !$omp private(vel) &
    !$omp shared(JJS,JJE,IIS,IIE,KS,KE,mom,val,DENS,flux,GSQRT,MAPF,num_diff)
    !$acc kernels
    do j = JJS, JJE+1
    do i = IIS, IIE
    do k = KS, KE
#ifdef DEBUG
       call CHECK( __LINE__, mom(k,i  ,j) )
       call CHECK( __LINE__, mom(k,i,j-1) )

       call CHECK( __LINE__, val(k,i,j-1) )
       call CHECK( __LINE__, val(k,i,j) )

       call CHECK( __LINE__, val(k,i,j-2) )
       call CHECK( __LINE__, val(k,i,j+1) )

       call CHECK( __LINE__, val(k,i,j-3) )
       call CHECK( __LINE__, val(k,i,j+2) )

       call CHECK( __LINE__, val(k,i,j-4) )
       call CHECK( __LINE__, val(k,i,j+3) )

#endif
       vel = ( 0.5_RP * ( mom(k,i,j)+mom(k,i,j-1) ) ) &
           / ( DENS(k,i,j) )
       flux(k,i,j-1) = GSQRT(k,i,j) / MAPF(i,j,+1) * vel &
                   * ( F81 * ( val(k,i,j)+val(k,i,j-1) ) &
                     + F82 * ( val(k,i,j+1)+val(k,i,j-2) ) &
                     + F83 * ( val(k,i,j+2)+val(k,i,j-3) ) &
                     + F84 * ( val(k,i,j+3)+val(k,i,j-4) ) ) &
                   + GSQRT(k,i,j) * num_diff(k,i,j)
    enddo
    enddo
    enddo
    !$acc end kernels
#ifdef DEBUG
    k = IUNDEF; i = IUNDEF; j = IUNDEF
#endif



    return
  end subroutine ATMOS_DYN_FVM_fluxY_XVZ_cd8







end module scale_atmos_dyn_fvm_flux_cd8

!--
! vi:set readonly sw=4 ts=8
!
!Local Variables:
!mode: f90
!buffer-read-only: t
!End:
!
!++
